modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
[[mods]]
modId="inferenceexample"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${description}'''
[[dependencies.inferenceexample]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
side="BOTH"
[[dependencies.inferenceexample]]
modId="neoforge"
type="required"
versionRange="[21.1.227,)"
side="BOTH"
[[dependencies.inferenceexample]]
modId="localinferenceapi"
type="required"
versionRange="[0.1.0]"
ordering="AFTER"
side="BOTH"
