modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
[[mods]]
modId = "inferenceexample"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.inferenceexample]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.inferenceexample]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.inferenceexample]]
modId = "localinferenceapi"
mandatory = true
versionRange = "[1.0.2,)"
ordering = "AFTER"
side = "BOTH"
